package com.github.streackmc.regionquery;

import com.github.streackmc.StreackLib.StreackLib;
import com.github.streackmc.StreackLib.utils.HTTPServer;
import net.querz.nbt.io.NBTDeserializer;
import net.querz.nbt.io.NamedTag;
import net.querz.nbt.tag.CompoundTag;
import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.*;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.DataFormatException;
import java.util.zip.Inflater;

import static fi.iki.elonen.NanoHTTPD.newFixedLengthResponse;

/**
 * RegionQuery —— 轻量级区域文件InhabitedTime查询插件（修正版）
 * <p>
 * 通过HTTP接口接收 x、z 坐标，正确解析 .mca 区域文件中对应区块的 InhabitedTime，
 * 并与配置的阈值比较，返回 {destroy: true/false} 的JSON。
 * </p>
 *
 *
 * @author Generated by AI (DeepSeek)
 * @since 2026-05-08
 */
public class RegionQuery extends JavaPlugin {

    private Logger logger;

    /* ===========================================
     *  可配置参数（均来自 config.yml）
     * =========================================== */
    private String endpoint;
    private String worldContainer;
    private long inhabitedTimeThreshold;

    @Override
    public void onEnable() {
        this.logger = getLogger();

        // 【1】校验 StreackLib 是否已启用
        if (!Bukkit.getPluginManager().isPluginEnabled("StreackLib")) {
            logger.severe("StreackLib 未启用，插件无法继续运行。");
            Bukkit.getPluginManager().disablePlugin(this);
            return;
        }

        // 【2】加载配置文件
        saveDefaultConfig();
        reloadConfigParams();

        // 【3】注册 HTTP 路由
        HTTPServer httpServer = StreackLib.getHttpServer();
        if (httpServer == null) {
            logger.severe("StreackLib 内建 HTTP 服务器未启动，插件无法继续运行。");
            Bukkit.getPluginManager().disablePlugin(this);
            return;
        }

        try {
            httpServer.registerHandler(endpoint, session -> {
                if (!fi.iki.elonen.NanoHTTPD.Method.GET.equals(session.getMethod())) {
                    return newFixedLengthResponse(
                            fi.iki.elonen.NanoHTTPD.Response.Status.METHOD_NOT_ALLOWED,
                            "text/plain",
                            "Method GET Allowed Only."
                    );
                }

                try {
                    Map<String, String> params = session.getParms();
                    String xStr = params.get("x");
                    String zStr = params.get("z");

                    if (xStr == null || zStr == null) {
                        return newFixedLengthResponse(
                                fi.iki.elonen.NanoHTTPD.Response.Status.BAD_REQUEST,
                                "application/json",
                                "{\"error\": \"Missing x or z parameter\"}"
                        );
                    }

                    int x, z;
                    try {
                        x = Integer.parseInt(xStr);
                        z = Integer.parseInt(zStr);
                    } catch (NumberFormatException e) {
                        return newFixedLengthResponse(
                                fi.iki.elonen.NanoHTTPD.Response.Status.BAD_REQUEST,
                                "application/json",
                                "{\"error\": \"x and z must be integers\"}"
                        );
                    }

                    // 坐标转换
                    int chunkX = x >> 4;
                    int chunkZ = z >> 4;
                    int regionX = chunkX >> 5;
                    int regionZ = chunkZ >> 5;

                    String regionFileName = "r." + regionX + "." + regionZ + ".mca";
                    File serverRoot = Bukkit.getWorldContainer();
                    File regionDir = new File(serverRoot, worldContainer + File.separator + "region");
                    File regionFile = new File(regionDir, regionFileName);

                    boolean destroy;
                    if (!regionFile.exists()) {
                        // 区域文件不存在 → 从未有区块数据
                        destroy = true;
                    } else {
                        long inhabitedTime = readInhabitedTimeFromRegion(regionFile, chunkX, chunkZ);
                        destroy = (inhabitedTime == -1) || (inhabitedTime <= inhabitedTimeThreshold);
                        // -1 表示区块不存在或读取失败，也允许删除
                    }

                    String jsonResponse = String.format("{\"destroy\": %s}", destroy);
                    return newFixedLengthResponse(
                            fi.iki.elonen.NanoHTTPD.Response.Status.OK,
                            "application/json",
                            jsonResponse
                    );

                } catch (Exception e) {
                    logger.log(Level.SEVERE, "处理请求时发生异常", e);
                    return newFixedLengthResponse(
                            fi.iki.elonen.NanoHTTPD.Response.Status.INTERNAL_ERROR,
                            "application/json",
                            "{\"error\": \"Internal server error\"}"
                    );
                }
            });

            logger.info("RegionQuery 已注册端点: " + endpoint);
        } catch (Exception e) {
            logger.log(Level.SEVERE, "注册 HTTP 处理器失败: " + endpoint, e);
            Bukkit.getPluginManager().disablePlugin(this);
        }
    }

    @Override
    public void onDisable() {
        HTTPServer httpServer = StreackLib.getHttpServer();
        if (httpServer != null && endpoint != null) {
            httpServer.removeHandler(endpoint);
        }
        logger.info("RegionQuery 已卸载。");
    }

    private void reloadConfigParams() {
        reloadConfig();
        endpoint = getConfig().getString("endpoint", "/api/region/query");
        worldContainer = getConfig().getString("world-container", "world");
        inhabitedTimeThreshold = getConfig().getLong("inhabited-time-threshold", 3600000L);
        logger.info("配置已加载：endpoint=" + endpoint +
                ", world-container=" + worldContainer +
                ", inhabited-time-threshold=" + inhabitedTimeThreshold);
    }

    /**
     * 从 .mca 区域文件中读取指定区块的 InhabitedTime。
     *
     * @param regionFile 区域文件对象
     * @param chunkX     区块 X 坐标（全局坐标）
     * @param chunkZ     区块 Z 坐标（全局坐标）
     * @return 区块的 InhabitedTime，若区块不存在或读取失败则返回 -1
     */
    private long readInhabitedTimeFromRegion(File regionFile, int chunkX, int chunkZ) {
        // 区块在区域文件中的局部索引（0~1023）
        int localX = chunkX & 31;
        int localZ = chunkZ & 31;
        int index = localZ * 32 + localX;

        try (RandomAccessFile raf = new RandomAccessFile(regionFile, "r")) {
            // 1. 读取 Chunk Offset Table (4KiB 前部)
            raf.seek(index * 4);
            byte[] offsetBytes = new byte[4];
            raf.read(offsetBytes);
            int offsetSector = ByteBuffer.wrap(offsetBytes).order(ByteOrder.BIG_ENDIAN).getInt();
            if (offsetSector == 0) {
                // 区块数据不存在
                return -1;
            }
            int sectorCount = offsetSector & 0xFF;
            int chunkOffset = (offsetSector >> 8) * 4096; // 偏移量（字节）

            // 2. 读取区块头（前4字节为压缩长度，后1字节为压缩类型）
            raf.seek(chunkOffset);
            byte[] lengthBytes = new byte[4];
            raf.read(lengthBytes);
            int dataLength = ByteBuffer.wrap(lengthBytes).order(ByteOrder.BIG_ENDIAN).getInt();
            if (dataLength <= 0 || dataLength > sectorCount * 4096) {
                return -1;
            }

            byte compressionType = raf.readByte();
            // compressionType: 1 = GZip (旧版), 2 = Zlib (Anvil)
            if (compressionType != 1 && compressionType != 2) {
                return -1;
            }

            // 3. 读取压缩数据（剩余 dataLength - 1 字节）
            byte[] compressed = new byte[dataLength - 1];
            raf.read(compressed);

            // 4. 解压缩
            byte[] decompressed;
            if (compressionType == 1) {
                // GZip 解压（罕见，但支持）
                try (ByteArrayInputStream bais = new ByteArrayInputStream(compressed);
                     java.util.zip.GZIPInputStream gzip = new java.util.zip.GZIPInputStream(bais)) {
                    decompressed = gzip.readAllBytes();
                }
            } else {
                // Zlib 解压
                Inflater inflater = new Inflater();
                inflater.setInput(compressed);
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                byte[] buffer = new byte[8192];
                while (!inflater.finished()) {
                    int len = inflater.inflate(buffer);
                    baos.write(buffer, 0, len);
                }
                inflater.end();
                decompressed = baos.toByteArray();
            }

            // 5. 解析 NBT
            NBTDeserializer deserializer = new NBTDeserializer(true, false);
            NamedTag namedTag = deserializer.fromStream(new ByteArrayInputStream(decompressed));
            if (!(namedTag.getTag() instanceof CompoundTag)) {
                return -1;
            }
            CompoundTag levelTag = (CompoundTag) namedTag.getTag();
            // 注意：区块 NBT 根标签即为 "Level"，其内部包含 InhabitedTime
            if (!levelTag.containsKey("InhabitedTime")) {
                return -1;
            }
            return levelTag.getLong("InhabitedTime");
        } catch (IOException | DataFormatException e) {
            logger.log(Level.WARNING, "读取区域文件失败: " + regionFile.getAbsolutePath(), e);
            return -1;
        }
    }
}