package com.github.streackmc.regionquery;

import com.github.streackmc.StreackLib.StreackLib;
import com.github.streackmc.StreackLib.utils.HTTPServer;
import com.github.streackmc.StreackLib.utils.SConfig;
import net.querz.nbt.io.NBTDeserializer;
import net.querz.nbt.io.NamedTag;
import net.querz.nbt.tag.CompoundTag;
import net.querz.nbt.tag.Tag;
import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import static fi.iki.elonen.NanoHTTPD.newFixedLengthResponse;

/**
 * RegionQuery —— 轻量级区域文件InhabitedTime查询插件
 * <p>
 * 通过HTTP接口接收 x、z 坐标，转换为区块坐标后读取对应.mca文件中的InhabitedTime，
 * 并与配置的阈值比较，返回 {destroy: true/false} 的JSON。
 * </p>
 *
 * <h3>设计要点（最小化 & 可靠性）：</h3>
 * <ul>
 *   <li>仅包含一个主类，无额外依赖模块。</li>
 *   <li>配置文件只暴露必要参数（endpoint、world容器路径、阈值）。</li>
 *   <li>通过 {@code StreackLib.getHttpServer()} 获取共享HTTP服务器，
 *       避免自建server带来的端口、线程池等复杂性。</li>
 *   <li>NBT解析使用 querz NBT 库，与 StreackLib 内部实现一致。</li>
 *   <li>每个请求都独立读取并关闭文件流，保证异常时不泄漏资源。</li>
 *   <li>返回体量极小（固定JSON），性能开销低，满足“轻量”要求。</li>
 * </ul>
 *
 * @author Generated by AI (DeepSeek)
 * @since 2026-05-08
 */
public class RegionQuery extends JavaPlugin {

    private Logger logger;

    /* ===========================================
     *  可配置参数（均来自 config.yml）
     * =========================================== */
    private String endpoint;
    private String worldContainer;
    private long inhabitedTimeThreshold;

    @Override
    public void onEnable() {
        this.logger = getLogger();

        // 【1】校验 StreackLib 是否已启用
        if (!Bukkit.getPluginManager().isPluginEnabled("StreackLib")) {
            logger.severe("StreackLib 未启用，插件无法继续运行。");
            Bukkit.getPluginManager().disablePlugin(this);
            return;
        }

        // 【2】加载配置文件（最小化：仅三个键）
        saveDefaultConfig();
        reloadConfigParams();

        // 【3】注册 HTTP 路由
        HTTPServer httpServer = StreackLib.getHttpServer();
        if (httpServer == null) {
            logger.severe("StreackLib 内建 HTTP 服务器未启动，插件无法继续运行。");
            Bukkit.getPluginManager().disablePlugin(this);
            return;
        }

        try {
            httpServer.registerHandler(endpoint, session -> {
                // 仅允许 GET 请求
                if (!fi.iki.elonen.NanoHTTPD.Method.GET.equals(session.getMethod())) {
                    return newFixedLengthResponse(
                            fi.iki.elonen.NanoHTTPD.Response.Status.METHOD_NOT_ALLOWED,
                            "text/plain",
                            "Method GET Allowed Only."
                    );
                }

                try {
                    // 提取参数 x、z
                    Map<String, String> params = session.getParms();
                    String xStr = params.get("x");
                    String zStr = params.get("z");

                    if (xStr == null || zStr == null) {
                        return newFixedLengthResponse(
                                fi.iki.elonen.NanoHTTPD.Response.Status.BAD_REQUEST,
                                "application/json",
                                "{\"error\": \"Missing x or z parameter\"}"
                        );
                    }

                    int x, z;
                    try {
                        x = Integer.parseInt(xStr);
                        z = Integer.parseInt(zStr);
                    } catch (NumberFormatException e) {
                        return newFixedLengthResponse(
                                fi.iki.elonen.NanoHTTPD.Response.Status.BAD_REQUEST,
                                "application/json",
                                "{\"error\": \"x and z must be integers\"}"
                        );
                    }

                    // 【4】坐标转换：世界坐标 → 区块坐标 → 区域坐标 → 区域文件
                    // 世界坐标转区块坐标（向下取整除法）
                    int chunkX = x >> 4;   // 等价于 floor(x / 16.0)
                    int chunkZ = z >> 4;

                    // 区块坐标转区域坐标（右移5位，等价于除以32并向下取整） —— 来自 Minecraft Wiki
                    int regionX = chunkX >> 5;
                    int regionZ = chunkZ >> 5;

                    // 生成区域文件名：r.<regionX>.<regionZ>.mca
                    String regionFileName = "r." + regionX + "." + regionZ + ".mca";

                    // 构建区域文件路径：./worldContainer/region/<regionFile>
                    File serverRoot = Bukkit.getWorldContainer();
                    File regionDir = new File(serverRoot, worldContainer + File.separator + "region");
                    File regionFile = new File(regionDir, regionFileName);

                    // 【5】文件存在性检查
                    if (!regionFile.exists()) {
                        // 文件不存在 → 认为从未有人居住，返回 destroy = true
                        return newFixedLengthResponse(
                                fi.iki.elonen.NanoHTTPD.Response.Status.OK,
                                "application/json",
                                "{\"destroy\": true}"
                        );
                    }

                    // 【6】NBT 解析，读取 InhabitedTime
                    long inhabitedTime = 0;
                    try (InputStream fis = new FileInputStream(regionFile)) {
                        // querz NBT 库默认支持 GZIP 检测；区域文件均为 GZIP 压缩
                        NBTDeserializer deserializer = new NBTDeserializer(true, false);
                        NamedTag namedTag = deserializer.fromStream(fis);
                        Tag<?> rootTag = namedTag.getTag();

                        // 根应为 CompoundTag
                        if (!(rootTag instanceof CompoundTag)) {
                            return newFixedLengthResponse(
                                    fi.iki.elonen.NanoHTTPD.Response.Status.INTERNAL_ERROR,
                                    "application/json",
                                    "{\"error\": \"Invalid region file: root is not CompoundTag\"}"
                            );
                        }

                        CompoundTag root = (CompoundTag) rootTag;
                        // 读取区域文件中的 InhabitedTime（位于根下）
                        if (root.containsKey("InhabitedTime")) {
                            inhabitedTime = root.getLong("InhabitedTime");
                        } else {
                            // 若不存在此键，视为 0（纯净新世界）
                            inhabitedTime = 0;
                        }
                    } catch (Exception e) {
                        logger.log(Level.WARNING, "读取区域文件失败: " + regionFile.getAbsolutePath(), e);
                        return newFixedLengthResponse(
                                fi.iki.elonen.NanoHTTPD.Response.Status.INTERNAL_ERROR,
                                "application/json",
                                "{\"error\": \"Failed to read region file\"}"
                        );
                    }

                    // 【7】比较阈值，返回结果
                    boolean destroy = inhabitedTime <= inhabitedTimeThreshold;

                    String jsonResponse = String.format("{\"destroy\": %s}", destroy);
                    return newFixedLengthResponse(
                            fi.iki.elonen.NanoHTTPD.Response.Status.OK,
                            "application/json",
                            jsonResponse
                    );

                } catch (Exception e) {
                    logger.log(Level.SEVERE, "处理请求时发生异常", e);
                    return newFixedLengthResponse(
                            fi.iki.elonen.NanoHTTPD.Response.Status.INTERNAL_ERROR,
                            "application/json",
                            "{\"error\": \"Internal server error\"}"
                    );
                }
            });

            logger.info("RegionQuery 已注册端点: " + endpoint);
        } catch (Exception e) {
            logger.log(Level.SEVERE, "注册 HTTP 处理器失败: " + endpoint, e);
            Bukkit.getPluginManager().disablePlugin(this);
        }
    }

    @Override
    public void onDisable() {
        // 移除注册的处理器，避免残留死路由
        HTTPServer httpServer = StreackLib.getHttpServer();
        if (httpServer != null && endpoint != null) {
            httpServer.removeHandler(endpoint);
        }
        logger.info("RegionQuery 已卸载。");
    }

    /**
     * 从 config.yml 重新加载配置参数。
     */
    private void reloadConfigParams() {
        reloadConfig();
        endpoint = getConfig().getString("endpoint", "/api/region/query");
        worldContainer = getConfig().getString("world-container", "world");
        inhabitedTimeThreshold = getConfig().getLong("inhabited-time-threshold", 3600000L);
        logger.info("配置已加载：endpoint=" + endpoint +
                ", world-container=" + worldContainer +
                ", inhabited-time-threshold=" + inhabitedTimeThreshold);
    }
}